// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Feb 25 01:26:47 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "HomePanel.h"

// begin wxGlade: ::extracode
// end wxGlade


HomePanel::HomePanel(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: HomePanel::HomePanel
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(0, 0, 2, wxEXPAND, 0);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(sizer_5, 1, wxEXPAND, 0);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("Welcome to EveAware"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    label_1->SetFont(wxFont(23, wxFONTFAMILY_ROMAN, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_NORMAL, 0, wxT("")));
    sizer_5->Add(label_1, 0, wxEXPAND, 0);
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, wxT("Please Select Option"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    sizer_5->Add(label_2, 0, wxBOTTOM|wxEXPAND, 15);
    button_2 = new wxButton(this, wxID_ANY, wxT("button_2"));
    button_2->SetMinSize(wxSize(200, 50));
    sizer_5->Add(button_2, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    button_5 = new wxButton(this, wxID_ANY, wxT("button_5"));
    button_5->SetMinSize(wxSize(200, 50));
    sizer_5->Add(button_5, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    button_4 = new wxButton(this, wxID_ANY, wxT("button_4"));
    button_4->SetMinSize(wxSize(200, 50));
    sizer_5->Add(button_4, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_1->Add(0, 0, 2, wxEXPAND, 0);
    
    SetSizer(sizer_1);
    // end wxGlade
}

