// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Feb 25 01:26:47 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef HOMEPANEL_H
#define HOMEPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class HomePanel: public wxPanel {
public:
    // begin wxGlade: HomePanel::ids
    // end wxGlade

    HomePanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: HomePanel::attributes
    wxButton* button_2;
    wxButton* button_5;
    wxButton* button_4;
    // end wxGlade
}; // wxGlade: end class


#endif // HOMEPANEL_H
