// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Feb 25 01:26:47 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MYFRAME_H
#define MYFRAME_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include "HomePanel.h"
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: MyFrame::attributes
    HomePanel* HomePanel;
    // end wxGlade
}; // wxGlade: end class


#endif // MYFRAME_H
