// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Feb 25 01:26:47 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "MyFrame.h"

// begin wxGlade: ::extracode
// end wxGlade


MyFrame::MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    SetSize(wxSize(974, 1039));
    SetTitle(wxT("frame"));
    HomePanel = new HomePanel(this, wxID_ANY);
    Layout();
    // end wxGlade
}

