// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Tue Mar 17 02:29:55 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_HomePanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_HomePanel_Base::Cal_HomePanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_HomePanel_Base::Cal_HomePanel_Base
    HomePanelSizer = new wxBoxSizer(wxVERTICAL);
    Cal_MenuPanel = new wxPanel(this, wxID_ANY);
    Cal_MenuPanel->SetMinSize(wxSize(953, 200));
    HomePanelSizer->Add(Cal_MenuPanel, 0, wxBOTTOM|wxEXPAND, 8);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_1 = new wxStaticText(Cal_MenuPanel, wxID_ANY, wxT("Error"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    sizer_4->Add(label_1, 0, wxALL|wxEXPAND, 0);
    wxStaticLine* static_line_1 = new wxStaticLine(this, wxID_ANY);
    HomePanelSizer->Add(static_line_1, 0, wxALL|wxEXPAND, 0);
    Cal_ContentPanel = new wxPanel(this, wxID_ANY);
    HomePanelSizer->Add(Cal_ContentPanel, 1, wxEXPAND, 0);
    
    Cal_MenuPanel->SetSizer(sizer_4);
    SetSizer(HomePanelSizer);
    // end wxGlade
}

