// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Sat Mar 14 23:41:47 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef BACKGROUND_H
#define BACKGROUND_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class BackGround: public d {
public:
    // begin wxGlade: BackGround::ids
    enum {
        ID_Cal = 1002,
    };
    // end wxGlade

    BackGround(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: BackGround::attributes
    wxButton* button_1;
    wxButton* button_2;
    wxButton* button_3;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void CalButton(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // BACKGROUND_H
