// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Thu Mar 12 00:56:57 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CAL_HOMEPANEL_BASE_H
#define CAL_HOMEPANEL_BASE_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class Cal_HomePanel_Base: public wxPanel {
public:
    // begin wxGlade: Cal_HomePanel_Base::ids
    // end wxGlade

    Cal_HomePanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: Cal_HomePanel_Base::attributes
    wxPanel* m_TopMenuPanel;
    wxPanel* m_ContentPanel;
    // end wxGlade
}; // wxGlade: end class


#endif // CAL_HOMEPANEL_BASE_H
