// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Mon Mar 16 01:27:40 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_ContentPanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_ContentPanel_Base::Cal_ContentPanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_ContentPanel_Base::Cal_ContentPanel_Base
    // end wxGlade
}

