// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Mon Mar 16 01:27:40 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CAL_CONTENTPANEL_BASE_H
#define CAL_CONTENTPANEL_BASE_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class Cal_ContentPanel_Base: public wxPanel {
public:
    // begin wxGlade: Cal_ContentPanel_Base::ids
    // end wxGlade

    Cal_ContentPanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: Cal_ContentPanel_Base::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // CAL_CONTENTPANEL_BASE_H
