// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Mon Mar 16 01:27:40 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_Menu_Default_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_Menu_Default_Base::Cal_Menu_Default_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_Menu_Default_Base::Cal_Menu_Default_Base
    SetMinSize(wxSize(953, 200));
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("Error"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    sizer_4->Add(label_1, 0, wxALL|wxEXPAND, 0);
    
    SetSizer(sizer_4);
    // end wxGlade
}

