// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Mar 11 10:39:43 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_HomePanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_HomePanel_Base::Cal_HomePanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_HomePanel_Base::Cal_HomePanel_Base
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    m_TopMenuPanel = new wxPanel(this, wxID_ANY);
    m_TopMenuPanel->SetMinSize(wxSize(943, 200));
    sizer_2->Add(m_TopMenuPanel, 0, wxEXPAND, 0);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    sizer_4->Add(0, 0, 0, 0, 0);
    m_ContentPanel = new wxPanel(this, wxID_ANY);
    sizer_2->Add(m_ContentPanel, 1, wxEXPAND, 0);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    sizer_5->Add(0, 0, 0, 0, 0);
    
    m_ContentPanel->SetSizer(sizer_5);
    m_TopMenuPanel->SetSizer(sizer_4);
    SetSizer(sizer_2);
    // end wxGlade
}

