// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Mon Mar 16 01:27:40 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_HomePanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_HomePanel_Base::Cal_HomePanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_HomePanel_Base::Cal_HomePanel_Base
    HomePanelSizer = new wxBoxSizer(wxVERTICAL);
    Cal_MenuPanel = new Cal_Menu_Default_Base(this, wxID_ANY);
    HomePanelSizer->Add(Cal_MenuPanel, 0, wxBOTTOM|wxEXPAND, 8);
    wxStaticLine* static_line_1 = new wxStaticLine(this, wxID_ANY);
    HomePanelSizer->Add(static_line_1, 0, wxALL|wxEXPAND, 0);
    Cal_ContentPanel = new Cal_ContentPanel_Base(this, wxID_ANY);
    HomePanelSizer->Add(Cal_ContentPanel, 1, wxEXPAND, 0);
    
    SetSizer(HomePanelSizer);
    // end wxGlade
}

