// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Sun Mar 15 00:50:57 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Cal_Menu_ModeSelect_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


Cal_Menu_ModeSelect_Base::Cal_Menu_ModeSelect_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: Cal_Menu_ModeSelect_Base::Cal_Menu_ModeSelect_Base
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("Please Select Mode"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    label_1->SetFont(wxFont(16, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, 0, wxT("")));
    sizer_1->Add(label_1, 0, wxEXPAND, 0);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_2->Add(0, 20, 1, wxEXPAND, 0);
    button_1 = new wxButton(this, ID_Cal, wxT("cal"));
    button_1->SetMinSize(wxSize(150, 50));
    sizer_2->Add(button_1, 0, 0, 0);
    button_2 = new wxButton(this, wxID_ANY, wxT("button_2"));
    button_2->SetMinSize(wxSize(150, 50));
    sizer_2->Add(button_2, 0, 0, 0);
    button_3 = new wxButton(this, wxID_ANY, wxT("button_3"));
    button_3->SetMinSize(wxSize(150, 50));
    sizer_2->Add(button_3, 0, 0, 0);
    sizer_2->Add(20, 20, 1, wxEXPAND, 0);
    sizer_1->Add(20, 20, 1, wxEXPAND, 0);
    
    SetSizer(sizer_1);
    // end wxGlade
}


BEGIN_EVENT_TABLE(Cal_Menu_ModeSelect_Base, wxPanel)
    // begin wxGlade: Cal_Menu_ModeSelect_Base::event_table
    EVT_BUTTON(ID_Cal, Cal_Menu_ModeSelect_Base::CalButton)
    // end wxGlade
END_EVENT_TABLE();


void Cal_Menu_ModeSelect_Base::CalButton(wxCommandEvent &event)  // wxGlade: Cal_Menu_ModeSelect_Base.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (Cal_Menu_ModeSelect_Base::CalButton) not implemented yet"));
}


// wxGlade: add Cal_Menu_ModeSelect_Base event handlers

