// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Mar  4 00:19:20 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "delete.h"

// begin wxGlade: ::extracode
// end wxGlade


delete::delete(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: delete::delete
    SetSize(wxSize(974, 1039));
    SetTitle(wxT("frame"));
    IntroPanel_Base = new IntroPanel_Base(this, wxID_ANY);
    Layout();
    // end wxGlade
}

