// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Mar 11 10:39:43 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DELETE_H
#define DELETE_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include "Cal_HomePanel_Base.h"
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class Delete: public wxFrame {
public:
    // begin wxGlade: Delete::ids
    // end wxGlade

    Delete(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: Delete::attributes
    wxMenuBar* Delete_menubar;
    Cal_HomePanel_Base* Cal_HomePanel_Base;
    // end wxGlade
}; // wxGlade: end class


#endif // DELETE_H
