// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Wed Mar 11 10:39:43 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "Delete.h"

// begin wxGlade: ::extracode
// end wxGlade


Delete::Delete(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: Delete::Delete
    SetSize(wxSize(974, 1039));
    SetTitle(wxT("frame"));
    Delete_menubar = new wxMenuBar();
    wxMenu *wxglade_tmp_menu;
    wxglade_tmp_menu = new wxMenu();
    wxglade_tmp_menu->Append(wxID_ANY, wxT("\n                "), wxEmptyString);
    Delete_menubar->Append(wxglade_tmp_menu, wxT("File"));
    wxglade_tmp_menu = new wxMenu();
    Delete_menubar->Append(wxglade_tmp_menu, wxT("About"));
    SetMenuBar(Delete_menubar);
    wxBoxSizer* Delete_Sizer = new wxBoxSizer(wxHORIZONTAL);
    Cal_HomePanel_Base = new Cal_HomePanel_Base(this, wxID_ANY);
    Delete_Sizer->Add(Cal_HomePanel_Base, 1, wxEXPAND, 0);
    
    SetSizer(Delete_Sizer);
    Layout();
    // end wxGlade
}

