// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Mon Mar  9 10:23:04 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "HomePanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


HomePanel_Base::HomePanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, style)
{
    // begin wxGlade: HomePanel_Base::HomePanel_Base
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(0, 0, 0, 0, 0);
    sizer_2->Add(0, 0, 0, 0, 0);
    sizer_2->Add(0, 0, 0, 0, 0);
    
    SetSizer(sizer_2);
    // end wxGlade
}

