// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Fri Mar  6 20:30:00 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef INTROPANEL_BASE_H
#define INTROPANEL_BASE_H

#include <wx/wx.h>
#include <wx/image.h>


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class IntroPanel_Base: public wxPanel {
public:
    // begin wxGlade: IntroPanel_Base::ids
    // end wxGlade

    IntroPanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
    // begin wxGlade: IntroPanel_Base::attributes
    wxButton* GetStartedButton;
    wxButton* TutorialButton;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void GetStartedClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void TutorialClick(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // INTROPANEL_BASE_H
