// -*- C++ -*-
//
// generated by wxGlade 1.1.1 on Sun Mar  8 01:05:02 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "IntroPanel_Base.h"

// begin wxGlade: ::extracode
// end wxGlade


IntroPanel_Base::IntroPanel_Base(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: IntroPanel_Base::IntroPanel_Base
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(0, 0, 2, wxEXPAND, 0);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(sizer_5, 0, wxALL|wxEXPAND, 0);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, wxT("Welcome to EveAware"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    label_1->SetFont(wxFont(23, wxFONTFAMILY_ROMAN, wxFONTSTYLE_ITALIC, wxFONTWEIGHT_NORMAL, 0, wxT("")));
    sizer_5->Add(label_1, 0, wxEXPAND, 0);
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, wxT("Please Select Option"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    sizer_5->Add(label_2, 0, wxBOTTOM|wxEXPAND, 15);
    GetStartedButton = new wxButton(this, ID_GetStartedButton, wxT("Get Started"));
    GetStartedButton->SetMinSize(wxSize(200, 50));
    sizer_5->Add(GetStartedButton, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    TutorialButton = new wxButton(this, ID_TutorialButton, wxT("Tutorial"));
    TutorialButton->SetMinSize(wxSize(200, 50));
    sizer_5->Add(TutorialButton, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    sizer_2->Add(0, 0, 2, wxEXPAND, 0);
    
    SetSizer(sizer_2);
    // end wxGlade
}


BEGIN_EVENT_TABLE(IntroPanel_Base, wxPanel)
    // begin wxGlade: IntroPanel_Base::event_table
    EVT_BUTTON(ID_GetStartedButton, IntroPanel_Base::GetStartedClick)
    EVT_BUTTON(ID_TutorialButton, IntroPanel_Base::TutorialClick)
    // end wxGlade
END_EVENT_TABLE();


void IntroPanel_Base::GetStartedClick(wxCommandEvent &event)  // wxGlade: IntroPanel_Base.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (IntroPanel_Base::GetStartedClick) not implemented yet"));
}

void IntroPanel_Base::TutorialClick(wxCommandEvent &event)  // wxGlade: IntroPanel_Base.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (IntroPanel_Base::TutorialClick) not implemented yet"));
}


// wxGlade: add IntroPanel_Base event handlers

